name: Deploy site
on: pull_request
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    steps:
      - name: Check the environment
        if: ${{ secrets.FLEEK_TOKEN == '' }}
        run: 'echo "invalid env"'
      - name: Checkout this branch
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12
      - name: Install Fleek CLI
        run: npm i -g @fleek-platform/cli
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build & deploy sites
        run: fleek sites deploy
